apiVersion: v1
kind: Service
metadata:
  name: {{ include "abs-adapter-diasoft.fullname" . }}
  labels:
    {{- include "abs-adapter-diasoft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9002
      protocol: TCP
      name: http
  selector:
    {{- include "abs-adapter-diasoft.selectorLabels" . | nindent 4 }}
