apiVersion: v1
kind: Service
metadata:
  name: {{ include "abs-adapter-rs-bank.fullname" . }}
  labels:
    {{- include "abs-adapter-rs-bank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9003
      protocol: TCP
      name: http
  selector:
    {{- include "abs-adapter-rs-bank.selectorLabels" . | nindent 4 }}
