apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-service.fullname" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "billing-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "billing-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: billing-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8096
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: AUDIT_URL
              value: {{ .Values.env.AUDIT_URL | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8096
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
