apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abs-connector.fullname" . }}
  labels:
    {{- include "abs-connector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "abs-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "abs-connector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: abs-connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8093
              protocol: TCP
          env:
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
            - name: AUDIT_URL
              value: {{ .Values.env.AUDIT_URL | quote }}
            - name: ADAPTER_URLS
              value: {{ .Values.env.ADAPTER_URLS | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8093
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8093
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
