apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff-admin.fullname" . }}
  labels:
    {{- include "bff-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8095
      protocol: TCP
      name: http
  selector:
    {{- include "bff-admin.selectorLabels" . | nindent 4 }}
