apiVersion: v1
kind: Service
metadata:
  name: {{ include "ext-rosfinmon.fullname" . }}
  labels:
    {{- include "ext-rosfinmon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8091
      protocol: TCP
      name: http
  selector:
    {{- include "ext-rosfinmon.selectorLabels" . | nindent 4 }}
