all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    masters:
      hosts:
        master-01:
          ansible_host: 192.168.10.11
        master-02:
          ansible_host: 192.168.10.12
        master-03:
          ansible_host: 192.168.10.13
    workers:
      hosts:
        worker-01:
          ansible_host: 192.168.10.21
        worker-02:
          ansible_host: 192.168.10.22
        worker-03:
          ansible_host: 192.168.10.23
        worker-04:
          ansible_host: 192.168.10.24
    databases:
      hosts:
        db-01:
          ansible_host: 192.168.10.31
        db-02:
          ansible_host: 192.168.10.32
    storage:
      hosts:
        storage-01:
          ansible_host: 192.168.10.41
        storage-02:
          ansible_host: 192.168.10.42
        storage-03:
          ansible_host: 192.168.10.43
        storage-04:
          ansible_host: 192.168.10.44
