apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bff-onboarding.fullname" . }}
  labels:
    {{- include "bff-onboarding.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bff-onboarding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bff-onboarding.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: bff-onboarding
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8094
              protocol: TCP
          env:
            - name: ONBOARDING_URL
              value: {{ .Values.env.ONBOARDING_URL | quote }}
            - name: CLIENT_URL
              value: {{ .Values.env.CLIENT_URL | quote }}
            - name: DOCUMENT_URL
              value: {{ .Values.env.DOCUMENT_URL | quote }}
            - name: AUDIT_URL
              value: {{ .Values.env.AUDIT_URL | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8094
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8094
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
