# Overrides for temporal helm chart
server:
  replicaCount: 1
  config:
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          database: temporal

frontend:
  service:
    type: ClusterIP
    port: 7233

ui:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
