apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "risk-engine.fullname" . }}
  labels:
    {{- include "risk-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "risk-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "risk-engine.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: risk-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: RULES_PATH
              value: {{ .Values.env.RULES_PATH | quote }}
            - name: AUDIT_URL
              value: {{ .Values.env.AUDIT_URL | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
