global:
  imageRegistry: ""
  imageTag: "latest"
  imagePullPolicy: IfNotPresent
  postgresql:
    host: postgresql
    port: 5432
    database: aibank
    existingSecret: aibank-postgresql
    secretKey: postgresql-password
  redis:
    host: redis-master
    port: 6379
  kafka:
    brokers: "kafka:9092"
  temporal:
    address: "temporal-frontend:7233"
  vault:
    address: "http://vault:8200"
  istio:
    enabled: true

api-gateway:
  replicaCount: 2

tenant-service:
  replicaCount: 1

onboarding-orchestrator:
  replicaCount: 2
