apiVersion: v1
kind: Service
metadata:
  name: {{ include "abs-adapter-cft.fullname" . }}
  labels:
    {{- include "abs-adapter-cft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    {{- include "abs-adapter-cft.selectorLabels" . | nindent 4 }}
